name: Deploy Zola Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAGES_BRANCH: master
          BUILD_DIR: website
          COMMIT_MESSAGE: "Deploy generated Zola site to master [skip ci]"
